Jarvis-Presentacion/Areas/TransitoConexion/Controllers/TransitoConexionController.cs
//Todo
//using Microsoft.AspNetCore.Authorization;
//using Microsoft.AspNetCore.Identity.UI.Services;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.Extensions.Configuration;
//using Microsoft.Extensions.Logging;
//using Opain.Jarvis.Dominio.Entidades;
//using Opain.Jarvis.Presentacion.Web.Helpers;
//using System;
//using System.Collections.Generic;
//using System.Globalization;
//using System.Linq;
//using System.Threading.Tasks;


//using Opain.Jarvis.Dominio.Entidades;
//using iTextSharp.text;
//using iTextSharp.text.pdf;
//using System.IO;
//using System.Net.Http;
//using System.Net;
//using System.IO.Compression;
//using ClosedXML.Excel;
//using Opain.Jarvis.Presentacion.Web.Areas.CargaInformacion.Controllers;
//using iTextSharp.text.html.simpleparser;
//using DocumentFormat.OpenXml.Office2010.Excel;

//namespace Opain.Jarvis.Presentacion.Web.Areas.TransitoConexion.Controllers
//{
//    [Authorize(Roles = "AEROLINEA,SUPERVISOR,OPAIN,ADMINISTRADOR")]
//    [Area("TransitoConexion")]
//    public class TransitoConexionController : Controller
//    {
//        private readonly IConfiguration configuration;
//        private readonly IServicioApi servicioApi;
//        private readonly IEmailSender emailSender;
//        private readonly ILogger<TransitoConexionController> _logger;
//        private static List<PasajeroTransitoOtd> pasajeroTransitoOtd = new List<PasajeroTransitoOtd>();

//        public TransitoConexionController(IConfiguration cfg, IServicioApi api, IEmailSender email, ILogger<TransitoConexionController> logger)
//        {
//            configuration = cfg;
//            servicioApi = api;
//            emailSender = email;
//            _logger = logger;
//        }

//        protected async Task<IList<PasajeroTransitoOtd>> AccionesPrincipal()
//        {
//            TransitoRequest oFiltro = new TransitoRequest();
//            string rutaRelativaAero = configuration.GetSection("URIs:AerolineaObtenerTodos").Value;
//            IList<AerolineaOtd> lstAerolineas = await servicioApi.GetAsync<IList<AerolineaOtd>>(rutaRelativaAero);
//            ViewData["Aerolineas"] = lstAerolineas;

//            //string rutaRelativa = configuration.GetSection("URIs:TransitoConexionPrincipal").Value;

//            //List<PasajeroTransitoOtd> pasajeros = new List<PasajeroTransitoOtd>();
//            Opain.Jarvis.Presentacion.Web.Bussiness.PasajerosTransito oList = new Bussiness.PasajerosTransito();            
//            IList<PasajeroTransitoOtd> oListTransitos = await oList.TransitosEnTramite(User, configuration, servicioApi, oFiltro);

//            //IList<PasajeroTransitoOtd> pasajeros = null;
//            //pasajeros = await servicioApi.GetAsync<IList<PasajeroTransitoOtd>>(rutaRelativa).ConfigureAwait(false);

//            //pasajeros = pasajeros
//            //    .Where(x => x.TTC == 1 && x.TTL == 0)
//            //    .ToList();
//            return oListTransitos;
//        }

//        [Authorize(Roles = "AEROLINEA,SUPERVISOR,OPAIN,ADMINISTRADOR")]
//        public async Task<IActionResult> Principal(string Download = "")
//        {
//            ViewBag.Download = "NA";
//            if (Download != "")
//            {
//                ViewBag.Download = Download;
//                ViewBag.extension =  Path.GetExtension(Download);
//            }
//            //// Cargo las aerolineas
//            //string rutaRelativaAero = configuration.GetSection("URIs:AerolineaObtenerTodos").Value;
//            //IList<AerolineaOtd> lstAerolineas = await servicioApi.GetAsync<IList<AerolineaOtd>>(rutaRelativaAero);
//            //ViewData["Aerolineas"] = lstAerolineas;

//            //string rutaRelativa = configuration.GetSection("URIs:TransitoConexionPrincipal").Value;

//            IList<PasajeroTransitoOtd> pasajeros = await AccionesPrincipal();
//            //    await servicioApi.GetAsync<IList<PasajeroTransitoOtd>>(rutaRelativa).ConfigureAwait(false);


//            //pasajeros = pasajeros
//            //    .Where(x => x.TTC == 1 && x.TTL == 0)
//            //    .ToList();

//            return View(pasajeros);
//        }
//        [Authorize(Roles = "AEROLINEA,SUPERVISOR,OPAIN,ADMINISTRADOR")]

//        [HttpGet]
//        public async Task<IActionResult> PrincipalDownload(string Download)
//        {
//            IList<PasajeroTransitoOtd> pasajeros = await AccionesPrincipal();

//            ViewBag.Download = false;
//            return View(pasajeros);
//        }

//        [Authorize(Roles = "AEROLINEA,SUPERVISOR")]
//        [HttpPost]
//        public async Task<IActionResult> Firmar(List<string> chkAprobar, List<string> chkRechazar, string pdfyexcel)
//        {
//            /*FileResult*/
//            //MemoryStream archivoDescarga = null;
//            string archivoDescarga = string.Empty;
//            try
//            {
//                int contAprobar = 0;
//                List<TransitoRechazado> transitosRechazados = new List<TransitoRechazado>();
//                List<PasajeroTransitoOtd> listaPasajeroTransitoOtd = new List<PasajeroTransitoOtd>();
//                int contTotal = 0;
//                int contTotalTTL = 0;
//                int contTotalTTC = 0;
//                List<int> idVuelos = new List<int>();


//                if (chkAprobar.Count > 0)
//                {
//                    DateTime fechaHoraFirma = DateTime.Now;
//                    foreach (var item in chkAprobar)
//                    {
//                        contAprobar = contAprobar + 1;
//                        contTotal = contTotal + 1;
//                        string[] datoss = item.Split(',');
//                        string id = datoss[0];
//                        string fecha = datoss[1];
//                        string hora = datoss[2];

//                        string rutaRelativa = string.Format(configuration.GetSection("URIs:TransitoConexionFirmar").Value, id);
//                        PasajeroTransitoOtd respuesta = await servicioApi.GetAsync<PasajeroTransitoOtd>(rutaRelativa).ConfigureAwait(false);
//                        respuesta.Firmado = 1;
//                        respuesta.FechaHoraFirma = fechaHoraFirma;
//                        string rutaRelativaActualizar = configuration.GetSection("URIs:TransitoConexionFirmar2").Value;
//                        await servicioApi.PostAsync<bool>(rutaRelativaActualizar, respuesta);
//                        // Actualizo el estado de vuelo si todos los transitos en conexión de ese vuelo ya fueron firmados
//                        int IdOperacionVuelo = respuesta.Operacion;
//                        AgregarVuelo(idVuelos, respuesta.Operacion);
//                        string rutaRelativa2 = string.Format(configuration.GetSection("URIs:ActualizarVuelosFirmados").Value, IdOperacionVuelo);
//                        await servicioApi.PostAsync<int>(rutaRelativa2, IdOperacionVuelo);
//                        // Actualizo la fecha y hora
//                        PasajeroTransitoOtd transito = await ObtenerTransito(Convert.ToInt32(id));

//                        if (fecha != null)
//                        {
//                            DateTime tempDate = Convert.ToDateTime(fecha);//DateTime.ParseExact(fecha, "M/dd/yyyy", CultureInfo.InvariantCulture);
//                            transito.FechaLlegada = tempDate;
//                        }

//                        if (hora != null)
//                        {
//                            transito.HoraLlegada = hora;
//                        }

//                        string rutaRelativa22 = configuration.GetSection("URIs:TransitosActualizar").Value;
//                        await servicioApi.PostAsync<bool>(rutaRelativa22, transito);


//                        listaPasajeroTransitoOtd.Add(transito);

//                    }
//                    //Generar Reporte pdf O excel
//                    if (listaPasajeroTransitoOtd != null && listaPasajeroTransitoOtd.ToString() != "" && listaPasajeroTransitoOtd.Count >= 1)
//                    {
//                        switch (pdfyexcel)
//                        {
//                            //1
//                            case "pdf":
//                                archivoDescarga = await DescargarTransitoConexionPDF(listaPasajeroTransitoOtd);
//                                break;
//                            //2
//                            case "excel":
//                                archivoDescarga = await DescargarTransitoConexionExcel(listaPasajeroTransitoOtd);
//                                break;

//                            default:
//                                break;
//                        }
//                    }

//                }

//                if (chkRechazar.Count > 0)
//                {
//                    DateTime fechaHoraFirma = DateTime.Now;

//                    foreach (var item in chkRechazar)
//                    {
//                        contTotal = contTotal + 1;


//                        string[] datoss = item.Split(',');
//                        string id = datoss[0];
//                        string fecha = datoss[1];
//                        string hora = datoss[2];

//                        string rutaRelativa = string.Format(configuration.GetSection("URIs:TransitoConexionFirmar").Value, id);
//                        PasajeroTransitoOtd respuesta = await servicioApi.GetAsync<PasajeroTransitoOtd>(rutaRelativa).ConfigureAwait(false);
//                        respuesta.Firmado = 2;
//                        respuesta.FechaHoraFirma = fechaHoraFirma;
//                        string rutaRelativaActualizar = configuration.GetSection("URIs:TransitoConexionFirmar2").Value;
//                        await servicioApi.PostAsync<bool>(rutaRelativaActualizar, respuesta);
//                        // Actualizo el estado de vuelo si todos los tránsitos en conexión de ese vuelo ya fueron firmados

Jarvis-Presentacion/Areas/TransitoConexion/ViewComponents/EntregadosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Opain.Jarvis.Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Opain.Jarvis.Presentacion.Web.Areas.TransitoConexion.ViewComponents
{
    public class EntregadosViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(List<PasajeroTransitoOtd> transitos, List<AerolineaOtd> lstAerolineas)
        {
            ClaimsPrincipal user = User as ClaimsPrincipal;
            DateTime fechaLimite = DateTime.Now.AddDays(1);

            string aerolinea = "";

            try
            {
                aerolinea = user.Claims.FirstOrDefault(c => c.Type.Equals("NombreAerolinea")).Value;
            }
            catch (Exception)
            {
                aerolinea = "";
            }

            List<PasajeroTransitoOtd> entregados = transitos.Where(x => x.Firmado == 0).Where(x => x.FechaHoraCargue < fechaLimite).ToList();
            int idAerolinea = Convert.ToInt32(user.Claims.FirstOrDefault(c => c.Type.Equals("IdAerolinea")).Value);

            // Traigo la abreviatura de la aerolina
            string Abreviatura = "";
            if (idAerolinea == 0)
            {
                entregados = entregados.ToList();
            }
            else
            {
                Abreviatura = lstAerolineas.Where(p => p.Id == idAerolinea).FirstOrDefault().Sigla;
                if (!string.IsNullOrEmpty(aerolinea))
                {
                    
                    entregados = entregados.Where(x => x.AerolineaLlegada.Equals(Abreviatura.ToUpper().Trim())).ToList();
                }
            }


            return View(entregados);
        }
    }
}

Jarvis-Presentacion/Areas/TransitoConexion/ViewComponents/RecibidosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Opain.Jarvis.Dominio.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Opain.Jarvis.Presentacion.Web.Areas.TransitoConexion.ViewComponents
{
    public class RecibidosViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(List<PasajeroTransitoOtd> transitos)
        {
            ClaimsPrincipal user = User as ClaimsPrincipal;
            DateTime fechaLimite = DateTime.Now.AddDays(1);

            string aerolinea = "";

            try
            {
                aerolinea = user.Claims.FirstOrDefault(c => c.Type.Equals("SiglaAerolinea")).Value;
            }
            catch (Exception)
            {
                aerolinea = "";
            }

            List<PasajeroTransitoOtd> recibidos = transitos.Where(x => x.FechaHoraCargue < fechaLimite).ToList();

            if (!string.IsNullOrEmpty(aerolinea))
            {
                recibidos = recibidos.Where(x => x.AerolineaSalida.Equals(aerolinea)).ToList();
            }

            return View(recibidos);
        }
    }
}

Jarvis-Presentacion/Areas/TransitoConexion/Views/TransitoConexion/Actualizar.cshtml
@model Opain.Jarvis.Dominio.Entidades.PasajeroTransitoOtd

<h1>
    ACTUALIZAR TRANSITO
</h1>

<div class="row">
    <div class="col-12">
        <form asp-action="Actualizar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <input type="hidden" asp-for="Operacion" />
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="TTC" />
                <input type="hidden" asp-for="TTL" />
                <input type="hidden" asp-for="FechaHoraCargue" />
                <input type="hidden" asp-for="NumeroVueloLlegada" />
                <input type="hidden" asp-for="FechaSalida" />
                <input type="hidden" asp-for="HoraSalida" />
                <input type="hidden" asp-for="NumeroVueloSalida" />
                <input type="hidden" asp-for="NombrePasajero" />
                <div class="form-group col-6">
                    <label asp-for="FechaLlegada" class="control-label"></label>
                    <input asp-for="FechaLlegada" class="form-control" />
                    <span asp-validation-for="FechaLlegada" class="text-danger"></span>
                </div>
                <div class="form-group col-6">
                    <label asp-for="HoraLlegada" class="control-label"></label>
                    <input asp-for="HoraLlegada" class="form-control" />
                    <span asp-validation-for="HoraLlegada" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <button type="button" class="btn btn--default--grey btn-block" data-dismiss="modal">Cancelar</button>
                </div>
                <div class="form-group col-6">
                    <button type="submit" class="btn btn--default btn-block">Actualizar</button>
                </div>
            </div>
        </form>
    </div>
</div>

Jarvis-Presentacion/Areas/TransitoConexion/Views/TransitoConexion/Principal.cshtml
@model IEnumerable<Opain.Jarvis.Dominio.Entidades.PasajeroTransitoOtd>

@{
    ViewData["Title"] = "Tránsitos y Conexiones";
}

<div id="divMsg"></div>
<h1>Tránsitos y Conexiones</h1>

@*<!-- Nav tabs -->*@
<ul class="nav nav-pills mb-3 justify-content-center" id="pills-tab" role="tablist">
    <li class="nav-item airplane__button">
        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">
            Pasajeros de llegada
            <img src="~/images/avion-tab.png" class="airplane__tab" alt="Llegada" />
            <span class="arrow-tab"></span>
        </a>
    </li>
    <li>
        <img src="~/images/mundo-tab.png" alt="" />
    </li>
    <li class="nav-item airplane__button">
        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">
            <img src="~/images/avion-tab.png" class="airplane__tab" alt="Salida" />
            Pasajeros de salida
            <span class="arrow-tab"></span>
        </a>
    </li>
</ul>

<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

        @*<!---Content Table----->*@
        <form asp-action="Firmar" method="post" id="formularioFirmar">
            <div class="bg--white">
                @if (User.IsInRole("AEROLINEA") || User.IsInRole("SUPERVISOR"))
                {
                    <div class="row">
                        <div class="col-sm-12">
                            A continuación se muestra la información de los pasajeros que fueron entregados a otras aerolíneas. Para finalizar el proceso seleccione los correspondientes pasajeros y de clic en "Firmar y guardar".
                        </div>
                    </div>
                    <hr />

                    <fieldset>
                        <legend>Seleccione el reporte a generar: </legend>
                        <p id="output"></p>

                        @{
                            if (ViewBag.Download != null && ViewBag.Download!="NA")
                            {
                                string TypeFile = ViewBag.extension; // "pdf"; 
                                string URLGet = "/Download?pdfyexcel=" + TypeFile + "&filename=" + ViewBag.Download;
                                //string URLGet = "~/Download?pdfyexcel=" + TypeFile+ "&filename=" + ViewBag.Download;
                                //string URLGet = "https://52.45.221.179/Download?pdfyexcel=" + TypeFile + "&filename=" + ViewBag.Download;
                                if (TypeFile != ".pdf")
                                {
                                    //URLGet = "https://52.45.221.179/Download?pdfyexcel=" + TypeFile + "&filename=" + ViewBag.Download;
                                    //URLGet = "~/Download?pdfyexcel=" + TypeFile + "&filename=" + ViewBag.Download;
                                    URLGet = "/Download?pdfyexcel=" + TypeFile + "&filename=" + ViewBag.Download;
                                    //TypeFile = "excel";
                                }
                                <script>
                                    var TypeFile = '@TypeFile';
                                    var URLPE = '@URLGet';
                                    URLPE = URLPE.replace('&amp;', '&');
                                    function UnMomento() {
                                        window.location.href = URLPE;                                        
                                    }
                                    setTimeout(UnMomento, 5000);
                                </script>
                            }
                        }                       

                        <div>
                            @*<img src="~/images/pdf.png" alt="Descargar PDF" />
                            <input type="radio" id="pdf" name="pdfyexcel" value="pdf" checked>
                            <label for="pdf">PDF</label>*@

                            <img src="~/images/xls.png" alt="Descargar Excel" />
                            <input type="radio" id="excel" name="pdfyexcel" value="excel" checked>
                            <label for="excel">Excel</label>
                        </div>
                        <div id="results"></div>
                    </fieldset>
                    <hr />
                }
                <div class="table-responsive-lg">
                    @await Component.InvokeAsync("Entregados", new { transitos = Model, lstAerolineas = ViewData["Aerolineas"] })
                </div>

            </div>
            @if (User.IsInRole("AEROLINEA") || User.IsInRole("SUPERVISOR"))
            {
                <button type="button" class="btn btn--default btn-block mt-3 mb-5" style="display:none" id="btnconfirmaFirma" data-toggle="modal" data-target=".advertencia">Firmar y guardar</button>
                <button type="button" class="btn btn--default btn-block mt-3 mb-5" style="display:none" id="btnconfirmaFirma2" data-toggle="modal" data-target=".Rechazados">v</button>
                <button type="button" id="btnGuardarFirmar" class="btn btn--default btn-block mt-3 mb-5"> Firmar y guardar</button>

            }

        </form>
    </div>

    <div class="tab-pane fade mb-5" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="bg--white">
            @if (User.IsInRole("AEROLINEA") || User.IsInRole("SUPERVISOR"))
            {
                <div class="d-flex">
                    <div class="flex-grow-1 pt-2 pb-2">
                        A continuación se muestra la información de los pasajeros que fueron recibidos por las aerolíneas
                    </div>
                </div>
                <hr />
            }

            <div class="table-responsive-lg">
                @await Component.InvokeAsync("Recibidos", new { transitos = Model })
            </div>
        </div>
    </div>
</div>

@if (User.IsInRole("AEROLINEA") || User.IsInRole("SUPERVISOR"))
{
    <!--Modal advertencia-->
    <div class="modal fade advertencia" id="modalMensaje" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="margin-right:0px!important; padding-right:0px!important">
        <div class="modal-dialog modal--full">
            <div class="modal-content">
                <div class="modal-header">
                    <img src="~/images/advertencia.png" class="img-fluid" alt="Advertencia" />
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="col-sm-6 offset-sm-3">
                            <p>
                                ¿Esta seguro(a) que desea firmar y guardar?
                            </p>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-8 offset-sm-2">
                                <button type="button" id="btnFirmar" class="btn btn--default btn-block">Aceptar</button>
                            </div>
                            @*<div class="col-sm-6 offset-sm-2">
                                    <button type="button" id="btnCerrar" class="btn btn--default btn-block" data-dismiss="modal">Cerrar</button>
                                </div>*@
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Model validarechazo-->
    <div class="modal fade Rechazados" id="modalMensajerec" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="margin-right:0px!important; padding-right:0px!important">
        <div class="modal-dialog modal--full">
            <div class="modal-content">
                <div class="modal-header">
                    <img src="~/images/advertencia.png" class="img-fluid" alt="Advertencia" />
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="col-sm-6 offset-sm-3">
                            <p>
                                Escribir una observaci&oacute;n para el rechazo de los tr&aacute;nsitos
                                <input type="text" style="width:200px; height:50px;" name="txtObservacion" id="txtObservacion" value="" />
                            </p>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-8 offset-sm-2">
                                <button type="button" id="btnFirmar22" class="btn btn--default btn-block">Aceptar</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Modal acciones-->
    <div class="modal bd-example-modal-lg" id="accionesTransito">
        <div class="modal-dialog modal--big">

            <div class="modal-content">
                <div class="modal-header">
                    <div class="row">
                        <div class="col-sm-4 offset-sm-2">
                            <button type="button" class="btn btn-block" data-dismiss="modal">
                                <img src="~/images/cerra.png" alt="Cerrar" />
                            </button>
                        </div>
                    </div>
                </div>
                <div class="modal-body">
                    <div id="divMensaje"></div>
                    <div class="container" id="divAcciones"></div>
                </div>
            </div>
        </div>
    </div>
}


<div class="modal fade advertencia guardadoCorrecto" id="myModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal--full">
        <div class="modal-content">
            <div class="modal-body">
                <div class="container">
                    <div class="col-sm-6 offset-sm-3 mt-4">
                        <p>
                            Sus cambios han sido
                            <br />
                            guardados correctamente
                        </p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6 offset-sm-3">
                            <button type="button" class="btn btn--default btn-block" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
        {
    <script type="text/javascript">

        $('#Firmar input[type=radio]').change(function () {
            //alert(this.value);
        });

    </script>




}